### ISSUE TITLE
Trouble crawling https sites

### ISSUE THREAD

**Issue by andrew-morales** [seethroughtrees/status-crawler#13]
Hello I am kind of new to programming so forgive me if this is a simple question but I have been able to use you tool against http sites with no issue but I am having trouble getting it to work with a https site. It hits the first page and returns null indicating that it did not crawl the exits. Do you have any suggestion to get it to work with an https site. Thank you.

**Comment by seethroughtrees** [comment]
Hey @andrew-morales ,

That's a really common issue when using phantomjs.  The first thing I'd do is look into ```--ignore-ssl-errors flag```.  You should be able to pass any phantomjs flags through the script.  If that doesn't work, there's a couple of other phantomjs flags for protocol etc...

http://phantomjs.org/api/command-line.html
